<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Verify Document — ShulePRO</title>
<style>
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    min-height: 100vh; background: #0f2942; color: #2d3748;
    display: flex; align-items: center; justify-content: center; padding: 1rem;
}
.card { background: #fff; border-radius: 14px; padding: 2rem; width: 100%; max-width: 460px; box-shadow: 0 10px 40px rgba(0,0,0,.3); }
h1 { font-size: 1.25rem; color: #0f2942; margin-bottom: .25rem; }
p.sub { color: #718096; font-size: .85rem; margin-bottom: 1.25rem; }
input[type=text] {
    width: 100%; padding: .8rem; font-size: 1.05rem; letter-spacing: 2px; text-transform: uppercase;
    border: 2px solid #cbd5e0; border-radius: 8px; font-family: monospace;
}
button { margin-top: .75rem; width: 100%; padding: .8rem; border: 0; border-radius: 8px; background: #c9a24b; color: #0f2942; font-weight: 700; font-size: 1rem; cursor: pointer; }
.result { margin-top: 1.25rem; padding: 1rem; border-radius: 10px; font-size: .9rem; }
.valid   { background: #e6f4ea; border: 1.5px solid #1f7a3f; }
.invalid { background: #fdecea; border: 1.5px solid #c0392b; }
.result h2 { font-size: 1rem; margin-bottom: .5rem; }
.result dt { font-weight: 600; color: #4a5568; font-size: .75rem; text-transform: uppercase; margin-top: .5rem; }
.result dd { margin: 0; }
.hash { font-family: monospace; font-size: .7rem; word-break: break-all; color: #718096; }
</style>
</head>
<body>
<div class="card">
    <h1>🔏 Document Verification</h1>
    <p class="sub">Enter the verification code printed on the document's digital signature block.</p>
    <form method="GET">
        <input type="text" name="code" placeholder="DOC-XXXXXXXXXX" value="{{ request('code') }}" required maxlength="20" autofocus>
        <button type="submit">Verify Document</button>
    </form>

    @if(request()->filled('code'))
        @if($signature)
        <div class="result valid">
            <h2>✅ Authentic document</h2>
            <dl>
                <dt>Document</dt><dd>{{ $signature->title }}</dd>
                <dt>Contents</dt><dd>{{ $signature->summary }}</dd>
                <dt>Generated by</dt><dd>{{ $signature->signer->name ?? 'System' }}</dd>
                <dt>Generated on</dt><dd>{{ $signature->created_at->format('d M Y, H:i:s') }}</dd>
                <dt>Integrity hash</dt><dd class="hash">{{ $signature->content_hash }}</dd>
            </dl>
            <p style="margin-top:.75rem;font-size:.8rem;color:#4a5568">
                Compare the hash prefix and details with the printed document. If anything differs,
                the paper copy has been altered.
            </p>
        </div>
        @else
        <div class="result invalid">
            <h2>❌ Unknown code</h2>
            <p>No document with code <strong>{{ strtoupper(request('code')) }}</strong> was ever issued
            by this system. The document is not authentic, or the code was mistyped.</p>
        </div>
        @endif
    @endif
</div>
</body>
</html>
