<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Aptitude Test Report - {{ $aptitudeAttempt->student->name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 14px; line-height: 1.5; }
        h2, h3, h4 { margin: 0; }
        .header { text-align: center; margin-bottom: 20px; }
        .section { margin-top: 20px; }
        .question { margin-bottom: 15px; padding: 10px; border: 1px solid #ccc; border-radius: 5px; }
        .question img { max-width: 400px; display: block; margin-top: 5px; }
        .option img { max-width: 200px; display: block; margin-top: 5px; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #555; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Aptitude Test Report</h2>
        <h3>{{ $aptitudeAttempt->student->name }} ({{ $aptitudeAttempt->student->admission_no }})</h3>
        <p>Counselor: {{ $aptitudeAttempt->counselor->name }}</p>
        <p>Date: {{ $aptitudeAttempt->created_at->format('d M Y, H:i') }}</p>
        <p><strong>Total Score:</strong> {{ $aptitudeAttempt->total_score }}</p>
    </div>

    @foreach($aptitudeAttempt->answers->groupBy(function($a){ return $a->question->section; }) as $section => $answers)
        <div class="section">
            <h4>{{ $section }}</h4>
            <hr>
            @foreach($answers as $answer)
                <div class="question">
                    <p><strong>Q{{ $loop->iteration }}. {!! $answer->question->question !!}</strong></p>

                    @if($answer->question->image)
                        <img src="{{ public_path('storage/'.$answer->question->image) }}" alt="Question Image">
                    @endif

                    <p><strong>Answer:</strong> 
                        @php
                            $ans = $answer->student_answer;
                            $display = '';
                            if(in_array($answer->question->type, ['mcq','true_false'])) {
                                $option = $answer->question->options[$ans] ?? null;
                                $display = $option['text'] ?? $ans;
                            } else {
                                $display = $ans;
                            }
                        @endphp
                        {!! $display !!}
                    </p>

                    <p><strong>Marks Obtained:</strong> {{ $answer->obtained_marks }} / {{ $answer->question->marks }}</p>
                </div>
            @endforeach
        </div>
    @endforeach

    <div class="footer">
        Generated by MEMA SMS &copy; {{ date('Y') }}
    </div>
</body>
</html>
