<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Every exported treasurer-office report is registered here with a
     * unique verification code and an HMAC of its contents. The code is
     * printed on the PDF; anyone can enter it on the public verification
     * page to confirm the document was genuinely generated by the system
     * and by whom — a tamper-evidence layer for printed/emailed reports.
     */
    public function up(): void
    {
        Schema::create('document_signatures', function (Blueprint $table) {
            $table->id();
            $table->foreignId('school_id')->nullable()->constrained()->cascadeOnDelete();
            $table->string('code', 20)->unique();
            $table->string('doc_type', 50);
            $table->string('title');
            $table->string('summary', 500)->nullable();
            $table->string('content_hash', 64);
            $table->foreignId('signed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('document_signatures');
    }
};
